apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
stringData:
  url: "postgresql://{{ .Values.app.database.user }}:{{ .Values.app.database.pw }}@{{ .Values.app.database.host }}:{{ .Values.app.database.port }}/{{ .Values.app.database.db }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-skb
stringData:
  skb: "{{ .Values.app.secretKeyBase }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pt
stringData:
  port: "{{ .Values.service.port }}"
