version: v1.0.0
kind: stack
name: "Flask App w/ React Frontend"
description: "Production ready flask web app."
config:
  meta: _PROJECT
  ingress: true
services:
  postgres_1:
    service: postgres
    inputs:
      port: "5432"
      user: postgres
      password: postgres
      database: postgres
      num_replicas: "1"
projects:
  flaskapp_1:
    project: flaskapp
    inputs:
      name: flaskapp
      db_host: self.service.postgres_1.output.host
      db_port: self.service.postgres_1.output.port
      db_user: self.service.postgres_1.output.user
      db_pass: self.service.postgres_1.output.password
      db_database: self.service.postgres_1.output.database
    values: {}
    build:
      tag: latest
      registry: ""
    deps:
      services:
        - postgres_1