version: v1.0.0
kind: stack
name: "Flask App w/ React Frontend"
description: "Production ready flask web app."
config:
  meta: _PROJECT
  ingress: true
services:
  postgres_1:
    service: postgresql
    values: {}
    inputs:
      port: "5432"
      user: postgres
      password: postgres
      database: postgres
      num_replicas: "1"
  nginx_ingress_controller_1:
    service: nginx-ingress-controller
    values: {}
    inputs: {}
projects:
  flaskapp_1:
    project: flaskapp
    inputs:
      name: flaskapp
      db_host: self.service.postgres_1.output.host
      db_port: self.service.postgres_1.output.port
      db_user: self.service.postgres_1.output.user
      db_pass: self.service.postgres_1.output.password
      db_database: self.service.postgres_1.output.database
    values: {}
    build:
      tag: latest
      registry: ""
    deps:
      services:
        - postgres_1
  createreactapp_1:
    project: createreactapp
    inputs:
      name: frontend
      ingress: "true"
    values:
      ingress:
        hosts:
          - name: localhost
            path: /
            servicePort: "8000"
      extraEnvVars:
        - name: API_HOST
          value: self.project.flaskapp_1.output.host
        - name: API_PORT
          value: "5000"
    build:
      tag: latest
      registry: ""
    deps:
      projects:
        - flaskapp_1
      services:
        - nginx_ingress_controller_1