version: v1.0.0
kind: stack
name: "Elixir Phoenix"
description: "Phoenix App"
services:
  postgres_1:
    service: postgresql
    values: {}
    inputs:
      port: "5432"
      user: postgres
      password: postgres
      database: postgres
      num_replicas: "1"
projects:
  phoenix_1:
    project: phoenix_app
    inputs:
      name: phoenix_app
    values:
      ingress:
        hosts:
          - host: "phoenix.torblet.app"
            paths:
              - path: /*
                pathType: Prefix
    build:
      tag: latest
      registry: ""