version: v1.0.0
kind: stack
name: "Elixir Phoenix React"
description: "Phoenix app with a separate React frontend."
services:
  postgres_1:
    service: postgresql
    values: {}
    inputs:
      port: "5432"
      user: postgres
      password: postgres
      database: postgres
      num_replicas: "1"
projects:
  phoenix_1:
    project: phoenix_app
    inputs:
      name: phoenix_app
      db_host: self.service.postgres_1.output.host
      db_port: self.service.postgres_1.output.port
      db_user: self.service.postgres_1.output.user
      db_pass: self.service.postgres_1.output.password
      db_database: self.service.postgres_1.output.database
      no_assets: "true"
      no_live: "true"
      no_html: "true"
    values:
      ingress:
        hosts:
          - host: "api.phoenix-react.torblet.app"
            paths:
              - path: /*
                pathType: Prefix
    build:
      tag: latest
      registry: ""
  createreactapp_1:
    project: createreactapp
    inputs:
      name: createreactapp
      ingress: "true"
    values:
      service:
        type: ClusterIP
      ingress:
        hostname: frontend.phoenix-react.torblet.app
      extraEnvVars:
        - name: API_HOST
          value: self.project.phoenix_1.output.host
        - name: API_PORT
          value: "5000"
    build:
      tag: latest
      registry: ""
