FROM node:18-alpine

# Install dependencies only when needed
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
WORKDIR /app
ENV NODE_ENV development
RUN apk add --no-cache libc6-compat

# Install dependencies based on the preferred package manager
COPY .env.local package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN yarn install

COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "run", "dev"]
